# Site settings
title: CLOUDLESS
email: cloudlab@urv.cat
url: https://github.com/jeromelachaud/freelancer-theme
description: "CLOUDLESS: Proyecto para desarrollar una plataforma de computación en el borde (Edge) para la creación y despliegue de Espacios de Datos abiertos (International Data Spaces). "
keywords: "CLOUDLESS, Cloud Computing, edge, plataforma, analisis de datos, espacios de datos abiertos"
meta_author: CloudLab

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3890cf #3890cf
  primary-rgb: "56,144,207" #"56,144,207"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: CLOUDLESS
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Project Coordinator
  - line: Dr. Pedro García López 
  - line: pedro.garcia@urv.cat

# Credits content
credits: 'Frelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
plugins:
  - jekyll-multiple-languages-plugin
languages: ["en", "es"]
exclude_from_localizations: ["javascript", "images", "css", "assets", "gallery"]
# default_locale_in_subfolder: true
baseurl_root: ""
